market/applications/venta/urls.py
#
from django.urls import path
from . import views

app_name = "venta_app"

urlpatterns = [
    path(
        'venta/index/', 
        views.AddCarView.as_view(),
        name='venta-index',
    ),
    path(
        'carshop/update/<pk>/', 
        views.CarShopUpdateView.as_view(),
        name='carshop-update',
    ),
    path(
        'carshop/delete/<pk>/', 
        views.CarShopDeleteView.as_view(),
        name='carshop-delete',
    ),
    path(
        'carshop/delete-all/', 
        views.CarShopDeleteAll.as_view(),
        name='carshop-delete_all',
    ),
    path(
        'venta/simple/', 
        views.ProcesoVentaSimpleView.as_view(),
        name='venta-simple',
    ),
    path(
        'venta/voucher/', 
        views.ProcesoVentaVoucherView.as_view(),
        name='venta-voucher',
    ),
    path(
        'venta/voucher-pdf/<pk>/', 
        views.VentaVoucherPdf.as_view(),
        name='venta-voucher_pdf',
    ),
    path(
        'venta/ultimas-ventas/', 
        views.SaleListView.as_view(),
        name='venta-list',
    ),
    path(
        'venta/delete/<pk>/', 
        views.SaleDeleteView.as_view(),
        name='venta-delete',
    ),
    
      path(
        'venta/delete/<pk>/', 
        views.SaleDeleteView.as_view(),
        name='venta-delete',
    ),  
      
    path(
     'add-cliente/',
     views.cliente_add,
     name='cliente-add'), 
    
    path(
         'voucher-pdf/<int:pk>/',
         views.VentaVoucherPdf.as_view(),
         name='venta-voucher-pdf'),   
    
]

market/market/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    # users app
    re_path('', include('applications.users.urls')),
    # producto app
    re_path('', include('applications.producto.urls')),
    # venta app
    re_path('', include('applications.venta.urls')),
    # caja app
    re_path('', include('applications.caja.urls')),
]

market/applications/venta/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_delete, post_save
#
from model_utils.models import TimeStampedModel

# local apps
from applications.producto.models import Product

#
from .managers import SaleManager, SaleDetailManager, CarShopManager
from .signals import update_stok_ventas_producto

class Cliente(models.Model):
    nombre = models.CharField("Nombre", max_length=100)
    apellido = models.CharField("Apellido", max_length=100, blank=True, null=True)
    dni = models.CharField("CI / RIF", max_length=11, unique=True, blank=True, null=True)
    telefono = models.CharField("Teléfono", max_length=15, blank=True, null=True)
    email = models.EmailField("Email", blank=True, null=True)
    direccion = models.TextField("Dirección", blank=True, null=True)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ['nombre']

    def __str__(self):
        return f"{self.nombre} {self.apellido or ''}".strip()





class Sale(TimeStampedModel):
    """Modelo que representa a una Venta Global"""

    # tipo recibo constantes
    BOLETA = '0'
    FACTURA = '1'
    SIN_COMPROBANTE = '2'
    # tipo pago constantes
    TARJETA = '0'
    CASH = '1'
    BONO = '2'
    OTRO = '3'
    #
    TIPO_INVOCE_CHOICES = [
        (BOLETA, 'Boleta'),
        (FACTURA, 'Factura'),
        (SIN_COMPROBANTE, 'Sin Comprobante'),
    ]

    TIPO_PAYMENT_CHOICES = [
        (TARJETA, 'Tarjeta'),
        (CASH, 'Cash'),
        (BONO, 'Bono'),
        (OTRO, 'Otro'),
    ]

    date_sale = models.DateTimeField(
        'Fecha de Venta',
    )
    count = models.PositiveIntegerField('Cantidad de Productos')
    amount = models.DecimalField(
        'Monto', 
        max_digits=10, 
        decimal_places=2
    )
    type_invoce = models.CharField(
        'TIPO',
        max_length=2,
        choices=TIPO_INVOCE_CHOICES
    )
    type_payment = models.CharField(
        'TIPO PAGO',
        max_length=2,
        choices=TIPO_PAYMENT_CHOICES
    )
    close = models.BooleanField(
        'Venta cerrada',
        default=False
    )
    anulate = models.BooleanField(
        'Venta Anulada',
        default=False,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='cajero',
        related_name="user_venta",
    )
    
    cliente = models.ForeignKey(
        Cliente,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Cliente",
        related_name="ventas_cliente"
    )


    objects = SaleManager()

    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'ventas'

    def __str__(self):
        return 'Nº [' + str(self.id) + '] - ' + str(self.date_sale)



class SaleDetail(TimeStampedModel):
    """Modelo que representa a una venta en detalle"""

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='producto',
        related_name='product_sale'
    )
    sale = models.ForeignKey(
        Sale,
        on_delete=models.CASCADE, 
        verbose_name='Codigo de Venta',
        related_name='detail_sale'
    )
    count = models.PositiveIntegerField('Cantidad')
    price_purchase = models.DecimalField(
        'Precio Compra', 
        max_digits=10, 
        decimal_places=3
    )
    price_sale = models.DecimalField(
        'Precio Venta', 
        max_digits=10, 
        decimal_places=2
    )
    tax = models.DecimalField(
        'Impuesto', 
        max_digits=5,
        decimal_places=2
    )
    anulate = models.BooleanField(default=False)
    #

    objects = SaleDetailManager()

    class Meta:
        verbose_name = 'Producto Vendido'
        verbose_name_plural = 'Productos vendidos'

    def __str__(self):
        return str(self.sale.id) + ' - ' + str(self.product.name)


class CarShop(TimeStampedModel):
    """Modelo que representa a un carrito de compras"""

    barcode = models.CharField(
        max_length=13,
        unique=True
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='producto',
        related_name='product_car'
    )
    count = models.PositiveIntegerField('Cantidad')
    
    objects = CarShopManager()

    class Meta:
        verbose_name = 'Carrito de compras'
        verbose_name_plural = 'Carrito de compras'
        ordering = ['-created']

    def __str__(self):
        return str(self.product.name)


# signals for venta
post_save.connect(update_stok_ventas_producto, sender=SaleDetail)

market/applications/venta/forms.py
# ventas/forms.py
from django import forms
from .models import Sale, Cliente


class VentaForm(forms.Form):
    barcode = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Código de barras',
                'class': 'input-group-field',
                'autofocus': 'autofocus',
            }
        )
    )
    count = forms.IntegerField(
        min_value=1,
        widget=forms.NumberInput(
            attrs={
                'value': '1',
                'class': 'input-group-field',
            }
        )
    )

    def clean_count(self):
        count = self.cleaned_data['count']
        if count < 1:
            raise forms.ValidationError('Ingrese una cantidad mayor a cero')
        return count


# ventas/forms.py
class VentaVoucherForm(forms.Form):
    cliente = forms.ModelChoiceField(
        queryset=Cliente.objects.all().order_by('nombre'),
        required=True,  # <-- Obligatorio
        empty_label="Selecciona un cliente *",  # <-- No None, pero con mensaje claro
        widget=forms.Select(attrs={
            'class': 'input-group-field',
            'style': 'width: 100%;',
            'id': 'id_cliente',
        })
    )

    type_payment = forms.ChoiceField(
        required=True,
        choices=Sale.TIPO_PAYMENT_CHOICES,
        widget=forms.Select(attrs={'class': 'input-group-field'})
    )
    type_invoce = forms.ChoiceField(
        required=True,
        choices=Sale.TIPO_INVOCE_CHOICES,
        widget=forms.Select(attrs={'class': 'input-group-field'})
    )

market/applications/venta/views.py
# django
import os
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    View,
    UpdateView,
    DeleteView,
    DeleteView,
    ListView
)
from django.views.generic.edit import (
    FormView
)
# local
from applications.producto.models import Product
from applications.utils import render_to_pdf
from applications.users.mixins import VentasPermisoMixin
#
from .models import Sale, SaleDetail, CarShop, Cliente
from .forms import VentaForm, VentaVoucherForm
from .functions import procesar_venta

import qrcode
from io import BytesIO
import base64

# ventas/views.py
class AddCarView(VentasPermisoMixin, FormView):
    template_name = 'venta/index.html'
    form_class = VentaForm
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["productos"] = CarShop.objects.all()
        context["total_cobrar"] = CarShop.objects.total_cobrar()
        context['form_voucher'] = VentaVoucherForm()
        context['clientes_activos'] = Cliente.objects.all().order_by('nombre')  # <= Añade esta línea
        return context

    def form_valid(self, form):
        barcode = form.cleaned_data['barcode']
        count = form.cleaned_data['count']
        try:
            producto = Product.objects.get(barcode=barcode)
            obj, created = CarShop.objects.get_or_create(
                barcode=barcode,
                defaults={
                    'product': producto,
                    'count': count
                }
            )
            if not created:
                obj.count += count
                obj.save()
        except Product.DoesNotExist:
            messages.error(self.request, 'Producto no encontrado.')
        
        return super().form_valid(form)
    


class CarShopUpdateView(VentasPermisoMixin, View):
    """ quita en 1 la cantidad en un carshop """

    def post(self, request, *args, **kwargs):
        car = CarShop.objects.get(id=self.kwargs['pk'])
        if car.count > 1:
            car.count = car.count - 1
            car.save()
        #
        return HttpResponseRedirect(
            reverse(
                'venta_app:venta-index'
            )
        )


class CarShopDeleteView(VentasPermisoMixin, DeleteView):
    model = CarShop
    success_url = reverse_lazy('venta_app:venta-index')


class CarShopDeleteAll(VentasPermisoMixin, View):
    
    def post(self, request, *args, **kwargs):
        #
        CarShop.objects.all().delete()
        #
        return HttpResponseRedirect(
            reverse(
                'venta_app:venta-index'
            )
        )


class ProcesoVentaSimpleView(VentasPermisoMixin, View):
    """ Procesa una venta simple """

    def post(self, request, *args, **kwargs):
        #
        procesar_venta(
            self=self,
            type_invoce=Sale.SIN_COMPROBANTE,
            type_payment=Sale.CASH,
            user=self.request.user,
        )
        #
        return HttpResponseRedirect(
            reverse(
                'venta_app:venta-index'
            )
        )


class ProcesoVentaVoucherView(VentasPermisoMixin, FormView):
    form_class = VentaVoucherForm
    success_url = '.'

    def form_valid(self, form):
        type_payment = form.cleaned_data['type_payment']
        type_invoce = form.cleaned_data['type_invoce']
        cliente = form.cleaned_data.get('cliente')  # Puede ser None

        # Procesamos la venta con cliente
        venta = procesar_venta(
            self=self,
            type_invoce=type_invoce,
            type_payment=type_payment,
            user=self.request.user,
            cliente=cliente  # <-- Pasamos el cliente
        )

        if venta:
            messages.success(self.request, f'Venta realizada con éxito. N°: {venta.id}')
            return HttpResponseRedirect(
                reverse('venta_app:venta-voucher_pdf', kwargs={'pk': venta.pk})
            )
        else:
            messages.error(self.request, 'No se pudo procesar la venta. El carrito está vacío.')
            return HttpResponseRedirect(reverse('venta_app:venta-index'))
                


class VentaVoucherPdf(View):
    def get(self, request, *args, **kwargs):
        venta = get_object_or_404(Sale, id=self.kwargs['pk'])
        detalle_productos = venta.detail_sale.all()

        # Determinar formato
        formato = request.GET.get('format', 'profesional')  # /venta/voucher-pdf/1/?format=thermal

        if formato == 'thermal':
            template_name = 'venta/voucher_thermal.html'
            filename = f"comprobante_{venta.id}_thermal.pdf"
        else:
            template_name = 'venta/voucher_profesional.html'
            filename = f"comprobante_{venta.id}.pdf"

        data = {
            'venta': venta,
            'detalle_productos': detalle_productos,
            'logo_url': request.build_absolute_uri('/static/img/logo.png'),
            # Solo agregar QR en versión profesional
            'qr_base64': self.generate_qr(venta) if formato != 'thermal' else None,
        }

        pdf = render_to_pdf(template_name, data)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="{filename}"'
            return response
        return HttpResponse("Error al generar PDF", status=500)

    def generate_qr(self, venta):
        import qrcode
        from io import BytesIO
        import base64

        qr_data = f"https://marketdj.com/venta/{venta.id}"
        qr_img = qrcode.make(qr_data, box_size=6)
        buffer = BytesIO()
        qr_img.save(buffer, format="PNG")
        return base64.b64encode(buffer.getvalue()).decode()


class SaleListView(VentasPermisoMixin, ListView):
    template_name = 'venta/ventas.html'
    context_object_name = "ventas" 

    def get_queryset(self):
        return Sale.objects.ventas_no_cerradas()



class SaleDeleteView(VentasPermisoMixin, DeleteView):
    template_name = "venta/delete.html"
    model = Sale
    success_url = reverse_lazy('venta_app:venta-index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.anulate = True
        self.object.save()
        # actualizmos sl stok y ventas
        SaleDetail.objects.restablecer_stok_num_ventas(self.object.id)
        success_url = self.get_success_url()

        return HttpResponseRedirect(success_url)
    
    
def cliente_add(request):
    if request.method == "POST":
        nombre = request.POST.get("nombre", "").strip()
        apellido = request.POST.get("apellido", "").strip()
        dni = request.POST.get("dni", "").strip()
        telefono = request.POST.get("telefono", "").strip()
        email = request.POST.get("email", "").strip()

        # Validación básica
        if not nombre:
            messages.error(request, "El nombre es obligatorio.")
            return redirect('venta_app:venta-index')

        # Evitar DNI duplicado (si se ingresa)
        if dni and Cliente.objects.filter(dni=dni).exists():
            messages.error(request, f"Ya existe un cliente con CI/RIF {dni}.")
            return redirect('venta_app:venta-index')

        # Crear cliente
        cliente = Cliente.objects.create(
            nombre=nombre,
            apellido=apellido,
            dni=dni,
            telefono=telefono,
            email=email,
        )

        messages.success(request, f"Cliente {cliente} registrado con éxito.")
        return redirect('venta_app:venta-index')
    

    

market/templates/venta/delete.html
{% extends "venta/base_venta.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h5 class="cell" style="margin-bottom: 1em; text-align: center;">¿Desea eliminar esta Venta?</h5>  
  <form class="cell medium-9 grid-x grid-margin-x align-center" 
    action="{% url 'venta_app:venta-delete' sale.id %}" method="POST">
    {% csrf_token %}
    
    <div class="cell medium-7">
        <div class="card cell">
            <div class="card-divider">
              <h3>Monto: {{ sale.amount }}</h3>
            </div>
            <div class="card-section">
              <h4>ID: {{ sale.id }}</h4>
              <p>FECHA: {{ sale.date_sale }}</p>
              <p>CANTIDAD PRODUCTOS: {{ sale.count }}</p>
              <p>TIPO DE COMPROBANTE: {{ sale.get_type_invoce_display }}</p>
              <p>TIPO DE PAGO: {{ sale.get_type_payment_display }}</p>
            </div>
        </div>
    </div>
    
    <div class="cell medium-6">
      <button type="submit" class="alert button">Eliminar</button>
      <a href="{% url 'venta_app:venta-index' %}" class="primary button clear">Cancelar</a>
    </div>
  </form>
</div>

{% endblock panel-content %}

market/templates/venta/index.html
{% extends "venta/base_venta.html" %}
{% load static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-stretch" style="padding: 1.5rem 0;">

  <!-- === BARRA DE BÚSQUEDA Y ACCIONES RÁPIDAS === -->
  <div class="cell grid-x grid-margin-x align-middle"
    style="margin-bottom: 1.5rem; background: #1a1a1a; color: white; border-radius: 0.75rem; padding: 1rem;">

    <!-- Búsqueda de producto -->
    <div class="cell medium-6">
      <form class="input-group" method="POST">{% csrf_token %}
        <span class="input-group-label" style="background: #6d28d9; color: white;">
          <i class="fi-barcode"></i>
        </span>
        {{ form.barcode }}
        {{ form.count }}
        <div class="input-group-button">
          <input type="submit" class="button" style="background: #ffae00; color: #1a1a1a; font-weight: 600;"
            value="Agregar">
        </div>
      </form>
    </div>

    <!-- Botón: Cobrar (único acceso al flujo de pago) -->
    <div class="cell medium-6 text-right">
      <button data-open="modal-seleccionar-cliente" class="button success expanded">
        <i class="fi-print"></i> Cobrar
      </button>
    </div>
  </div>

  <!-- === LISTA DE PRODUCTOS EN CARRITO === -->
  <div class="cell large-8">
    <h5 style="color: #333; margin-bottom: 1rem;">
      <i class="fi-shopping-cart"></i> Productos en Venta
    </h5>

    {% if productos %}
    <table class="hover stack"
      style="border: 1px solid #e2e8f0; border-radius: 0.5rem; overflow: hidden; box-shadow: 0 1px 6px rgba(0,0,0,0.1);">
      <thead style="background: #6d28d9; color: white;">
        <tr>
          <th style="border-top-left-radius: 0.5rem;">CÓDIGO</th>
          <th>NOMBRE</th>
          <th>PRECIO</th>
          <th>CANT.</th>
          <th style="border-top-right-radius: 0.5rem;">ACCIONES</th>
        </tr>
      </thead>
      <tbody>
        {% for producto in productos %}
        <tr style="transition: background 0.2s;">
          <td>{{ producto.barcode }}</td>
          <td>{{ producto.product.name }}</td>
          <td>S/ {{ producto.product.sale_price }}</td>
          <td>{{ producto.count }}</td>
          <td class="text-center">
            <div class="button-group compact">
              <form action="{% url 'venta_app:carshop-update' producto.id %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="button warning tiny" title="Restar 1">
                  <i class="fi-minus"></i>
                </button>
              </form>
              <form action="{% url 'venta_app:carshop-delete' producto.id %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="button alert tiny" title="Eliminar">
                  <i class="fi-x"></i>
                </button>
              </form>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="callout text-center"
      style="background: #f8fafc; color: #64748b; border: 1px dashed #cbd5e1; border-radius: 0.5rem; padding: 2rem;">
      <i class="fi-page-search" style="font-size: 2rem; opacity: 0.5;"></i>
      <p style="margin-top: 0.5rem;">No hay productos en el carrito.</p>
    </div>
    {% endif %}
  </div>

  <!-- === RESUMEN Y ACCIONES === -->
  <div class="cell large-4">
    <div class="callout primary"
      style="background: #6d28d9; color: white; text-align: center; border-radius: 0.75rem; padding: 1.5rem; box-shadow: 0 4px 12px rgba(109, 40, 217, 0.3);">
      <h5 style="margin: 0; opacity: 0.9;">Total a Cobrar</h5>
      <h2 style="margin: 0.5rem 0; font-size: 2rem; font-weight: 700;">S/ {{ total_cobrar|default:"0.00" }}</h2>
    </div>

    <br>

    <form action="{% url 'venta_app:carshop-delete_all' %}" method="POST">
      {% csrf_token %}
      <button type="submit" class="button alert hollow expanded"
        onclick="return confirm('¿Estás seguro de limpiar todo el carrito?');">
        <i class="fi-trash"></i> Limpiar Todo
      </button>
    </form>
  </div>

</div>

<!-- === MODAL 1: SELECCIONAR CLIENTE (SOLO LECTURA) === -->
<div class="reveal" id="modal-seleccionar-cliente" data-reveal style="max-width: 600px;">
  <h4 style="color: #1a1a1a;">
    <i class="fi-user"></i> Seleccionar Cliente
  </h4>

  <form id="form-voucher" action="{% url 'venta_app:venta-voucher' %}" method="POST">
    {% csrf_token %}

    <div class="grid-x grid-margin-x">

      <!-- Buscador de cliente (Select2) -->
      <div class="cell medium-12">
        <label>Buscar cliente por nombre o CI/RIF:</label>
        <select name="cliente" id="id_cliente_select" class="select2-cliente" style="width: 100%;" required>
          <option value="">Selecciona un cliente *</option>
          {% for cliente in clientes_activos %}
            <option value="{{ cliente.id }}">
              {{ cliente.nombre }} {{ cliente.apellido|default:"" }} 
              {% if cliente.dni %}(CI/RIF: {{ cliente.dni }}){% endif %}
            </option>
          {% endfor %}
        </select>
        <p class="form-error" id="error-cliente" style="color: #e3342f; font-size: 0.875rem; display: none;">
          Debe seleccionar un cliente.
        </p>
      </div>

      <!-- Botón para registrar nuevo cliente -->
      <div class="cell text-center" style="margin: 1rem 0;">
        <small>
          ¿No encuentras al cliente?
          <a data-open="modal-nuevo-cliente"
             style="color: #6d28d9; font-weight: 600; text-decoration: underline; cursor: pointer;">
            Registrar nuevo cliente
          </a>
        </small>
      </div>

      <!-- Tipo de Pago y Comprobante -->
      <div class="cell medium-6">
        <label>Tipo de Pago:</label>
        <div class="input-group">
          <span class="input-group-label" style="background: #4a5568; color: white;">
            <i class="fi-credit-card"></i>
          </span>
          <select name="type_payment" required style="padding: 0.5rem;">
            <option value="1">Cash</option>
            <option value="0">Tarjeta</option>
            <option value="2">Bono</option>
            <option value="3">Otro</option>
          </select>
        </div>
      </div>

      <div class="cell medium-6">
        <label>Tipo de Comprobante:</label>
        <div class="input-group">
          <span class="input-group-label" style="background: #4a5568; color: white;">
            <i class="fi-document"></i>
          </span>
          <select name="type_invoce" required style="padding: 0.5rem;">
            <option value="2">Sin Comprobante</option>
            <option value="0">Boleta</option>
            <option value="1">Factura</option>
          </select>
        </div>
      </div>

    </div>

    <div class="grid-x grid-margin-x" style="margin-top: 1.5rem;">
      <div class="cell text-right">
        <button type="button" class="button secondary" data-close style="margin-right: 0.5rem;">Cancelar</button>
        <button type="submit" class="button success">Confirmar Venta</button>
      </div>
    </div>
  </form>

  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<!-- === MODAL 2: REGISTRAR NUEVO CLIENTE (solo creación) === -->
<div class="reveal" id="modal-nuevo-cliente" data-reveal style="max-width: 500px;">
  <h4 style="color: #1a1a1a;">Registrar Nuevo Cliente</h4>

  <form id="form-nuevo-cliente" method="POST" action="{% url 'venta_app:cliente-add' %}">
    {% csrf_token %}

    <div class="grid-x grid-margin-x">
      <div class="cell">
        <label>Nombre *</label>
        <input type="text" name="nombre" required 
               style="width: 100%; padding: 0.5rem; border: 1px solid #ddd; border-radius: 4px;">
      </div>
      <div class="cell">
        <label>Apellido</label>
        <input type="text" name="apellido" 
               style="width: 100%; padding: 0.5rem; border: 1px solid #ddd; border-radius: 4px;">
      </div>
      <div class="cell">
        <label>CI / RIF</label>
        <input type="text" name="dni" maxlength="11" 
               style="width: 100%; padding: 0.5rem; border: 1px solid #ddd; border-radius: 4px;">
      </div>
      <div class="cell">
        <label>Teléfono</label>
        <input type="text" name="telefono" 
               style="width: 100%; padding: 0.5rem; border: 1px solid #ddd; border-radius: 4px;">
      </div>
      <div class="cell">
        <label>Email</label>
        <input type="email" name="email" 
               style="width: 100%; padding: 0.5rem; border: 1px solid #ddd; border-radius: 4px;">
      </div>
    </div>

    <div class="grid-x grid-margin-x" style="margin-top: 1.5rem;">
      <div class="cell text-right">
        <button type="button" class="button secondary" data-close style="margin-right: 0.5rem;">Cancelar</button>
        <button type="submit" class="button success">Registrar Cliente</button>
      </div>
    </div>
  </form>

  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

{% endblock panel-content %}

<!-- === CSS y JS: Select2 + Validación === -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script>
  $(document).ready(function() {
    // Inicializar Select2
    $('.select2-cliente').select2({
      placeholder: 'Buscar cliente por nombre o CI/RIF...',
      allowClear: true,
      dropdownParent: $('#modal-seleccionar-cliente'),
      width: '100%'
    });

    // Validación del formulario
    $('#form-voucher').on('submit', function(e) {
      const cliente = $('#id_cliente_select').val();
      const error = $('#error-cliente');

      if (!cliente) {
        e.preventDefault();
        error.show();
        $('#id_cliente_select').focus();
      } else {
        error.hide();
      }
    });

    // Cerrar modal de registro y abrir de selección
    $('#modal-nuevo-cliente').on('closed.zf.reveal', function() {
      $('#modal-seleccionar-cliente').foundation('open');
    });

    // Inicializar Foundation
    $(document).foundation();
  });
</script>